### PR TITLE
Renovate template try2

### PR DESCRIPTION
**Pull request by dnbute**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #<gh-issue-id>

Test URLs:
- Original: https://www.sunstar.com/
- Before: https://main--sunstar--hlxsites.hlx.live/
- After: https://renovate-template-2--sunstar--hlxsites.hlx.live/

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by sdmcraft** [comment]
I see the renovate bot creates branches named like this `renovate/eslint-plugin-import-2.x` . The `.` in it could be problematic as it would change the domsain name for the test url. Can we control the name of the branch created here?

**Comment by dnbute** [comment]
> I see the renovate bot creates branches named like this `renovate/eslint-plugin-import-2.x` . The `.` in it could be problematic as it would change the domsain name for the test url. Can we control the name of the branch created here?

Ooooh, so that was the problem, ok makes way more sense now, yeah I'll look into solving this

**Comment by sdmcraft** [comment]
> Ooooh, so that was the problem, ok makes way more sense now, yeah I'll look into solving this

This is what we had in sunstar-engg site https://github.com/hlxsites/sunstar-engineering/blob/main/.renovaterc.json 
Can the same thing work here?

**Comment by dnbute** [comment]
> > Ooooh, so that was the problem, ok makes way more sense now, yeah I'll look into solving this
> 
> This is what we had in sunstar-engg site https://github.com/hlxsites/sunstar-engineering/blob/main/.renovaterc.json Can the same thing work here?

When I asked `@tripod` about this he suggested not extending the helix-shared config and just using the default, the token they use is only for adobe repos, I guess we could maybe override that somehow but I'd need some help with that

**Comment by dnbute** [comment]
@sdmcraft do you want to merge this, see if it works, and then maybe open an issue in the boilerplate?

**Comment by sdmcraft** [comment]
> o you want to merge this, see if it works, and then maybe open an issue in the boilerplate?

Yes please

**Review by sdmcraft — APPROVED** [review]

**Pull request merged**
