### PR TITLE
Remove default hero auto blocking, added compact and white mixins

### PR DESCRIPTION
**Pull request by sdmcraft**
Test URLs:
- Original: https://www.sunstar.com/about/chairman-interview/
- Before: https://main--sunstar--hlxsites.hlx.live/about/chairman-interview
- After: https://chairman--sunstar--hlxsites.hlx.live/about/chairman-interview

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. cards
- [ ] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. cards (grid)
- [ ] Documented in sidekick library

- [x] New mixins introduced in this PR
**Mixin Name** :  compact, white
- [x] Documented in sidekick library

### CODE REVIEW

**Comment by dnbute** [comment]
>I'm a little surprised that the removal from the buildHeroBlock has no impact, apparently we didn't need it at all?

I think that we didn't use the hero autoblocking since usually the first thing in a document is the `breadcrumb`, now that we have a [PR](https://github.com/hlxsites/sunstar/pull/338) that autoblocks the `breadcrumb`, could we maybe keep the hero autoblocking? I'm not sure exactly how/if this would work, but I think it's worth discussing
cc @jindaliiita

**Comment by jindaliiita** [comment]
> > I'm a little surprised that the removal from the buildHeroBlock has no impact, apparently we didn't need it at all?
> 
> I think that we didn't use the hero autoblocking since usually the first thing in a document is the `breadcrumb` most of the time, now that we have a [PR](https://github.com/hlxsites/sunstar/pull/338) that autoblocks the `breadcrumb`, could we maybe keep the hero autoblocking? I'm not sure exactly how/if this would work, but I think it's worth discussing cc @jindaliiita

I think we should consider hero block and breadcrumb two separate components.

**Comment by dnbute** [comment]
> I think we should consider hero block and breadcrumb two separate components.

Yeah of course, what I was suggesting was to leverage the `breadcrumb` autoblocking alongside this `hero` autoblocking

1. We autoblock the breadcrumb
2. Check if the conditions are met for the hero autoblocking
3. If true, autoblock the hero as well

**Comment by sdmcraft** [comment]
I figured a simpler way out which does not require me to remove the hero auto-blocking. Hence reinstated it. Since that was the major discussion item in the PR and it no longer applies, I'll go ahead and merge this PR. Though if you have comments to add, please feel free to add.

**Pull request merged**
