### PR TITLE
Implement Hotspot for research Page

### LINKED ISSUE #555: Research Page > Map hover items
Japan team want to have a 1:1 version of the R&D Network Map:

image

Can you please create a custom block for this?

@sdmcraft

### PR DESCRIPTION
**Pull request by meejain**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes #555 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/research
- Before: https://main--sunstar--hlxsites.hlx.live/_drafts/meet/research
- After: https://issue555-hotspot--sunstar--hlxsites.hlx.live/_drafts/meet/research

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [ ] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. _cards (grid)_
- [ ] Documented in sidekick library

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

**Review by sdmcraft — COMMENTED** [review]
image
This section should only be visible in mobile view now that we have added the hotspot.

**Review by sdmcraft — COMMENTED** [review]
The hotspot on the original is visible only for width >= 992px . We should do the same. For smaller screens, the static image with accordian below it should be shown.

image

**Comment by jindaliiita** [comment]
AFAIR we have to raise PR in https://github.com/sunstar-global/sunstar

**Comment by meejain** [comment]
https://github.com/sunstar-global/sunstar/pull/20 created, taking care of all the above feedback. Closing this.

**Pull request closed without merging**
