### PR TITLE
Refactored align-right

### LINKED ISSUE #527: Background image section alignment bug
It seems we got a regression on the background image sections.

https://main--sunstar--sunstar-global.hlx.live/jp/about/chairman-interview

image

@dnbute @sdmcraft

### PR DESCRIPTION
**Pull request by dnbute**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes #527 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/jp/about/chairman-interview
- Before: https://main--sunstar--hlxsites.hlx.live/jp/about/chairman-interview
- After: https://i-527--sunstar--hlxsites.hlx.live/jp/about/chairman-interview

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [ ] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. _cards (grid)_
- [ ] Documented in sidekick library

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

**Comment by dnbute** [comment]
@ehrro @sdmcraft quickest fix I could pull off, but I think this might break some other page(s)

**Comment by ehrro** [comment]
Hello @dnbute the top part looks good now.

I don't know how we can align the bottom part on the right since we are not using the columns block (because we have a quote). 

image

Also we might need to check why this was done in the first place to make sure it doesn't break something other guys implemented.

Thanks

**Review by sdmcraft — APPROVED** [review]
LGTM. 
Nit: You may want to make the commit message a bit more descriptive.

**Comment by dnbute** [comment]
> LGTM. Nit: You may want to make the commit message a bit more descriptive.

Yeah wanted to get this out asap, my bad

**Comment by dnbute** [comment]
@ehrro I might be mistaken but I think you added the align-right? git blame is confused for me and shows another PR from a month ago

**Comment by ehrro** [comment]
The alight-right property in the section metadata (if you are referring to that) was added initially I think by @sdmcraft for this particular use case I believe.

**Pull request merged**
