### PR TITLE
Table variant added

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/jp/newsroom/news/20140306104241/
- Before: https://main--sunstar--hlxsites.hlx.live/jp/newsroom/20140306104241
- After: https://table-variant--sunstar--hlxsites.hlx.page/jp/newsroom/20140306104241

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [ ] Documented in sidekick library

- [ ] New variations introduced in this PR
**Variation Name** :  For e.g. _cards (grid)_
- [ ] Documented in sidekick library

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

**Comment by JiangLong2019** [comment]
@jindaliiita I think we need to add a text-align for some td tags.

https://table-variant--sunstar--hlxsites.hlx.page/_drafts/jiang/brands

image

**Comment by jindaliiita** [comment]
@JiangLong2019 you can check now

**Comment by JiangLong2019** [comment]
Looks good.

**Review by JiangLong2019 — APPROVED** [review]

**Comment by sdmcraft** [comment]
@jindaliiita , could you update the block library with this variant?

**Pull request merged**
