### PR TITLE
Overlap hero right text alignment

### LINKED ISSUE #278: Overlapping hero right block not properly on the right
image

The overlapping hero right block is not properly aligned.

The following code fixes the issue on line 338.

image

@media (min-width: 77rem)
.hero-banner.overlap .hero-banner-heading-container.right-text {
    padding-right: calc(50vw - 82.875rem / 2);
    left: unset;
    right: 0;
}

image

### PR DESCRIPTION
**Pull request by dnbute**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #278 

Test URLs:
- Original: https://www.sunstar.com/about/life-with-sunstar
- Before: https://main--sunstar--hlxsites.hlx.live/about/life-with-sunstar
- After: https://i-278--sunstar--hlxsites.hlx.live/about/life-with-sunstar

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Review by ehrro — CHANGES_REQUESTED** [review]
Hello @dnbute ,

I checked and this solution doesn't fix the positioning perfectly.

Can you please use the code I provided? It looks perfect if we invert the properties from left to right.

image

```css
.hero-banner.overlap .hero-banner-heading-container.right-text {
    padding-right: calc(50vw - 82.875rem / 2);
    left: unset;
    right: 0;
}
```

Thanks.

**Comment by dnbute** [comment]
@ehrro I think I misread what you said in the initial issue and didn't realise `pading-right` turned into `padding-left` so that's why I didn't do that from the start; I implemented your version now
The sustainability page also seems to change because of this so if you could check the visual differences reported by the bot that would be great
Thanks!

**Review by ehrro — CHANGES_REQUESTED** [review]
Sorry I missed that there are styles for tablet and desktop.

Can you make sure the styles are applied on both desktop and tablet?
image

image

image

You can remove the other properties that are conflicting as well.
image

Thank you

**Review by ehrro — APPROVED** [review]
All good in the hood.

**Pull request merged**
