### PR TITLE
Adding Download icon support in text block and light background variant

### LINKED ISSUE #363: Learn more sections, emphasis and download style inside text section

### PR DESCRIPTION
**Pull request by ehrro**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes #363 

## Changelog:
_Please enter each change as a new bullet point_

## Test URLs:
- Original: https://www.sunstar.com/jp/newsroom/news/20210330/
- Before: https://main--sunstar--hlxsites.hlx.live/jp/newsroom/20231002
- After: https://363--sunstar--hlxsites.hlx.live/jp/newsroom/20231002

## Library

- [ ] New Blocks introduced in this PR
      If yes, please provide details below
**Block Name** : For e.g. _cards_
- [ ] Documented in sidekick library

- [X] New variations introduced in this PR
 :  Text(light-background, download)
- [X] Documented in sidekick library
https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/text&index=5
https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/text&index=6

- [ ] New mixins introduced in this PR
**Mixin Name** :  For e.g. _compact, white_
- [ ] Documented in sidekick library

### CODE REVIEW

**Comment by ehrro** [comment]
Hello @jindaliiita. I know but I would like to use this light gray box and therefor all the links inside that box would need the download icon. To avoid having to put them manually all the time it would be easier to have that option available.

**Comment by jindaliiita** [comment]
Adding @dnbute and @rrrragas here also for their thoughts.
Because i still don't think download variant is required now.

**Comment by jindaliiita** [comment]
We have created one issue to deprecate this variant
https://github.com/hlxsites/sunstar/issues/344

**Comment by rrrragas** [comment]
> Adding @dnbute and @rrrragas here also for their thoughts. Because i still don't think download variant is required now.

> Yes , we have auto block which converts any link with download icon as downloadable. (Ex: PDF:download:)
https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/autoblock&index=1

**Comment by jindaliiita** [comment]
@ehrro One thing is pending here.
Currently on clicking download button its not downloading.

**Pull request merged**
