### PR TITLE
Columns with video

### PR DESCRIPTION
**Pull request by hparwani2**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #<gh-issue-id>

Test URLs:
- Original: https://www.sunstar.com/<path>
- Before: https://main--sunstar--hlxsites.hlx.live/about
- After: https://columns-with-video--sunstar--hlxsites.hlx.live/about

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Review by sdmcraft — COMMENTED** [review]
The video does not seem to play for me. 🤔

**Comment by hparwani2** [comment]
> The video does not seem to play for me. 🤔

@sdmcraft problem is occurring when you directly open /about page, but when you visit it from header it is working fine. looking into the RCA

**Comment by hparwani2** [comment]
@sdmcraft check now

**Comment by sdmcraft** [comment]
the video seems to be getting cropped in mobile screen,
image

**Review by sdmcraft — APPROVED** [review]

**Pull request merged**
