### PR TITLE
Added default margin to link block and variant no-margin

### LINKED ISSUE #303: Link / Button container default margin-bottom
Can you please 
1. add default margin bottom to link / button container$
2. add a variant no-margin if we don't want to add margin.

image
image

Thanks.

### PR DESCRIPTION
**Pull request by ehrro**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #303 

Test URLs:
- Before: https://main--sunstar--hlxsites.hlx.live/jp/sustainability/s-management/philosophy
- After: https://303--sunstar--hlxsites.hlx.live/jp/sustainability/s-management/philosophy

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Link   | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [x] New variations introduced in this PR

link(no-margin)    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Review by sdmcraft — COMMENTED** [review]
LGTM though we need to update the block library with this variant.

**Review by sdmcraft — APPROVED** [review]

**Comment by ehrro** [comment]
Hello @sdmcraft I added the variant in the sidekick:

image

**Comment by sdmcraft** [comment]
> Hello @sdmcraft I added the variant in the sidekick:

Ah ok. Likely I did'nt see as the PR description didn't mention the link to its location in the sidekick.
image

**Comment by ehrro** [comment]
Actually I added it after you said I needed to add it :D. Like 10 minutes ago.

**Pull request merged**
