### PR TITLE
Apply styles governing section margins/paddings to section-container

### LINKED ISSUE #308: Full width section with narrow, narrower or static container
https://main--sunstar--hlxsites.hlx.page/healthy-thinking/soft-picks-advanced1

image

### PR DESCRIPTION
**Pull request by sdmcraft**
Fixes #308 

Test URLs:
- Before: https://main--sunstar--hlxsites.hlx.live/healthy-thinking/soft-picks-advanced1
- After: https://i-308--sunstar--hlxsites.hlx.live/healthy-thinking/soft-picks-advanced1

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by dnbute** [comment]
The `history` page gets messed up a bit by this, should we also add styles for coloured backgrounds for only the `section-container`?

**Comment by dnbute** [comment]
Also autoblocking the space at the top seems to not work anymore

**Comment by sdmcraft** [comment]
> Also autoblocking the space at the top seems to not work anymore; see `business-performance` for example

Good catch. Addressed. Please take a look.

**Comment by dnbute** [comment]
> > Also autoblocking the space at the top seems to not work anymore; see `business-performance` for example
> 
> Good catch. Addressed. Please take a look.

All good on this!

**Review by bosschaert — APPROVED** [review]
LGTM

**Pull request merged**
