### PR TITLE
Default Global Typography Styles

### PR DESCRIPTION
**Pull request by ehrro**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #[<gh-issue-id>](https://github.com/hlxsites/sunstar/issues/171)

Test URLs:
- Before: https://main--sunstar--hlxsites.hlx.live/typography
- After: https://171-default-typography-styling--sunstar--hlxsites.hlx.live/typography

- [ ]  **If you are adding a new block or a variation to an existing block**, please fill below:

  Block library path: https://<branch>--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/<your-block>&index=0

### CODE REVIEW

**Comment by bosschaert** [comment]
I changed the test URLs to be .live ones instead of .page ones as those give a more consistent LHS.

As for the change ... as you can see from the visual results there is a lot of impact, but likely this is what you intended, so I'm going to give it my +1

**Review by bosschaert — APPROVED** [review]

**Comment by ehrro** [comment]
@sdmcraft @davidnuescheler @jindaliiita I am still going through the components/blocks to see if there are others UL / LI items.

**Comment by dnbute** [comment]
> I am still going through the components/blocks to see if there are others UL / LI items.

The Tabs here use lists https://171-default-typography-styling--sunstar--hlxsites.hlx.live/about/business-performance

**Review by sdmcraft — COMMENTED** [review]
@ehrro , thanks for contributing this. As I understand, you'd want to have global typography and then override it locally as needed. Please take a look at the visual differences reported in the PR and if it looks all fine to you, I think we should be good to merge.

**Comment by jindaliiita** [comment]
@ehrro @sdmcraft Currently social block which is being used on news and healthy thinking articles uses their own font properties, color and margin. So, will i remove these styles ?
h1 --> https://github.com/hlxsites/sunstar/blob/main/blocks/social/social.css#L110
h2 --> https://github.com/hlxsites/sunstar/blob/main/blocks/social/social.css#L33
h3 --> https://github.com/hlxsites/sunstar/blob/main/blocks/social/social.css#L146

**Review by jindaliiita — APPROVED** [review]

**Comment by ehrro** [comment]
Hello @jindaliiita I think we already spoke about your comment yesterday regarding the social block styling. I just want to confirm that you can keep your style as it is.

**Comment by ehrro** [comment]
Hello @sdmcraft I think we can merge this PR and will correct if necessary in another one.

**Review by sdmcraft — APPROVED** [review]

**Pull request merged**
