### PR TITLE
Healthy thinking page

### PR DESCRIPTION
**Pull request by sdmcraft**
Test URLs:
- Original: https://www.sunstar.com/healthy-thinking/
- Before: https://main--sunstar--hlxsites.hlx.page/healthy-thinking
- After: https://healthy-thinking--sunstar--hlxsites.hlx.page/healthy-thinking

- [x] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
Feed With Highlight | [doc-link](https://healthy-thinking--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/feed&index=2)

- [x] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
Section (Padded Inline)  | [doc-link](https://healthy-thinking--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/sections&index=11)
Section (Dark) | [doc-link](https://healthy-thinking--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/sections&index=12)
Columns(no-padding) | [doc-link](https://healthy-thinking--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/columns&index=15)

### CODE REVIEW

**Comment by JiangLong2019** [comment]
Some findings

1. About the links on the page, on the original site it opens the page in the same window rather than opening in a new window.

Ex.
image

2. Lose icon
image

3. The date shows above title, but sometimes it's under the title.
image

image

4. Content is different from original site.
image

5. "Read the reports" should show as a button.
image

6. Lose social media content. You can refer [Holistic Health Care](https://adobe.ly/405b5DH) for the authoring.
image

**Comment by sdmcraft** [comment]
@JiangLong2019 , thanks for the awesome review feedback with all the screenshots 🙏 . That made it so much easier to understand the feedback. I believe I have addressed all you feedback. Please take a look.

**Comment by JiangLong2019** [comment]
Looks good to me! 

Nit:
One small thing that Dejan may care about is the space between blocks is a little bit big.
image

**Comment by sdmcraft** [comment]
> 7 visual differences detected

I reviewed these differences and they are mostly minor margin/padding adjustments and looks ok after the changes as well.

**Comment by sdmcraft** [comment]
The PSI check for the [/healthy-thinking](https://healthy-thinking--sunstar--hlxsites.hlx.page/healthy-thinking) page passes. Rest all are block-library pages and can be omitted.

**Comment by bosschaert** [comment]
The left gutter is jumping a little which makes the page look less neat than the original one IMHO.

E.g. original:
Screenshot 2023-10-27 at 12 46 32

This pr:
Screenshot 2023-10-27 at 12 46 14

and further down, original:
Screenshot 2023-10-27 at 12 46 38

and this pr:
Screenshot 2023-10-27 at 12 46 21

Maybe it's not a big deal, but I find the original straight gutter just a little more pleasant to look at...

**Review by jindaliiita — APPROVED** [review]

**Comment by sdmcraft** [comment]
> The left gutter is jumping a little which makes the page look less neat than the original one IMHO.

Thanks for reviewing!
I have tried to address this to an extent. Please see screenshot below. 

The problem is that I am using blocks like `columns` and `hero-banner` which come with their own margin/paddings which have been defined based on where they are being used elsewhere. Now if I change those to match the requirements of this page, then the other pages where these blocks are being used would be impacted. 
The usual resort in such cases is to introduce a block variant to suit the styling requirements  of this page. I often try to avoid doing that as much as possible to avoid having lots of esoteric variants of a block in line with [this rule from the David N's model](https://www.aem.live/docs/davidsmodel#rule-9-number-of-blocks-and-variants). 

With that said, I did have to add a `no-padding` variant of the `columns` block here to avoid those margin/paddings and have everything left-aligned. I think this can be generally useful. The other part of your review comment pertains with the `hero-banner` being not left-aligned and the reasons are same. But I feel the `hero-banner` itself likely requires a rewrite as it seem to be unnecessarily complicated and I don't want add further complexity by adding another variant. I'll log a separate ticket to simplify the `hero-banner` block itself. 

I'll merge this PR as most of the review feedback is taken care of except the hero-banner alignment (for which I'll log a ticket to simplify the block itself). Hope that's fine. 

image

**Pull request merged**
