### PR TITLE
Restructure tag page - change the logic of tag rendering

### LINKED ISSUE #575: Restructure tag page - change the logic of tag rendering
Expected changes:
1. In feed block and breadcrumb, change the way of getting tag id identifier from url parameter to path. Ex, `feed-tags=XXX` -> `/tag/XXX`.
2. In tag block, change the tag link format from url parameter to path. Ex, `feed-tags=XXX` -> `/tag/XXX`.
3. Remove tag URL parameter redirection from 404.html
4. Redirect existing tag page URL to the new format.

### PR DESCRIPTION
**Pull request by JiangLong2019**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after), along with a short summary of changes:

## Issue

Fixes #575 

## Changelog:

1. In feed block and breadcrumb, change the way of getting tag id identifier from url parameter to path. Ex, feed-tags=XXX -> /tag/XXX.
2. In tag block, change the tag link format from url parameter to path. Ex, feed-tags=XXX -> /tag/XXX.
3. Remove tag URL parameter redirection from 404.html
4. Redirect existing tag page URL to the new format.

## Test URLs:
- Original: https://www.sunstar.com/healthy-thinking/tag?feed-tags=education
- Before: https://main--sunstar--hlxsites.hlx.live/healthy-thinking/tag?feed-tags=education
- After: https://issue575--sunstar--hlxsites.hlx.live/healthy-thinking/tag/education

### CODE REVIEW

**Comment by JiangLong2019** [comment]
@sdmcraft EDS doesn't support url parameters in redirect source URL, I'll try to find any other way to deal with it rather than redirects.xls
>Redirect existing tag page URL to the new format.

https://discord.com/channels/1131492224371277874/1207624789083168768/1207749171969265664

**Comment by jindaliiita** [comment]
Changes looks fine to me

**Comment by sdmcraft** [comment]
> @sdmcraft EDS doesn't support url parameters in redirect source URL, I'll try to find any other way to deal with it rather than redirects.xls
> 
> > Redirect existing tag page URL to the new format.
> 
> https://discord.com/channels/1131492224371277874/1207624789083168768/1207749171969265664

If query parameter based redirects are not possible then how would we solve the original problem i.e. having the right canonical url on the page?

**Comment by JiangLong2019** [comment]
@sdmcraft 
>If query parameter based redirects are not possible then how would we solve the original problem i.e. having the right canonical url on the page?

After the change, each tag page owns correct canonical url now. The problem is that we wanted to redirect current site tag page to the new tag page, let's say,
Current tag page - https://www.sunstar.com/healthy-thinking/tag?feed-tags=germany
New tag page - https://www.sunstar.com/healthy-thinking/tag/germany

In redirects.xls, the source URL doesn't support URL with parameter, we cannot use redirects.xls for the redirection. In my opinion, I don't think it's necessary, maybe we can ignore it.

**Comment by JiangLong2019** [comment]
@sdmcraft As we discussed, I've added the redirection for URL parameter tag page. Please have a check.
https://github.com/hlxsites/sunstar/pull/576/files#diff-fbceb58f32b99b8a5309251f8c49ac8eda82fba58b905c600c92bce1ed2a1c8c

**Review by sdmcraft — APPROVED** [review]

**Pull request merged**
