### PR TITLE
Refactor Hero Horizontal Tabs block to support button

### LINKED ISSUE #324: Refactor Hero Horizontal Tabs block to support button
Mobile view:
image

Tablet & Desktop view:
image

### PR DESCRIPTION
**Pull request by JiangLong2019**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fixes #324

Test URLs:
- Original: https://www.sunstar.com/healthy-thinking-report/oral-survey-2021
- Before: https://main--sunstar--hlxsites.hlx.live/healthy-thinking-report/oral-survey-2021
- After: https://hero-horizontal-tabs-button--sunstar--hlxsites.hlx.live/healthy-thinking-report/oral-survey-2021

- [ ] New Blocks introduced in this PR
      If yes, please provide details below

Block Name    | Documentation
------------- | -------------
 For e.g. cards | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=0)

- [ ] New variations introduced in this PR

Variation Name    | Documentation
------------- | -------------
 For e.g. cards (grid)  | [doc-link](https://main--sunstar--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/sidekick/blocks/cards&index=2)

### CODE REVIEW

**Comment by bosschaert** [comment]
Hi @JiangLong2019 the `hero-horizontal-tabs` block already has unit test coverage. Would it be an idea to add a few extra tests to cover this enhancement?

**Review by bosschaert — APPROVED** [review]

**Comment by dnbute** [comment]
@JiangLong2019 do you think we should maybe check if dejan is fine with the buttons being another color? It's only this page that has orange elements, maybe another color that's already used would work

**Comment by ehrro** [comment]
Hello @dnbute @bosschaert @JiangLong2019 for now I am fine with the orange color. We will work post migration to update these since it doesn't match our corporate identity. Thanks

**Comment by JiangLong2019** [comment]
@ehrro @dnbute Thanks, I'll keep the orange color. By the way, the reason way I used the orange color is that there are many icons with that color.

**Comment by JiangLong2019** [comment]
@bosschaert Nice point, I've added to the code.

**Pull request merged**
